version: "3.3"

networks:
  metrics:
    external: false

services:
  influxdb:
    image: influxdb:2.6-alpine
    # image: quay.io/influxdb/influxdb:v2.0.3
    container_name: tv-influxdb
    env_file: [./.env]
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      # - ./influxdb/influx.config.yml:/etc/influxdb2/config.yml
      - ./influxdb/init:/docker-entrypoint-initdb.d 
  telegraf:
    image: telegraf:latest
    restart: unless-stopped
    container_name: tv-telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
  grafana:
    image: grafana/grafana-oss:9.3.2
    env_file: [./.env]
    container_name: tv-grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "3030:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
