version: "3.3"

networks:
  metrics:
    name: "tv-metrics"
    external: false
  backend:
    name: "tv-backend"
    external: true

services:
  influxdb:
    image: influxdb:2.6-alpine
    container_name: tv-influxdb
    env_file: [./.env]
    restart: unless-stopped
    networks: ["metrics"]
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/init:/docker-entrypoint-initdb.d

  telegraf:
    image: telegraf:latest
    container_name: tv-telegraf
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    restart: unless-stopped
    networks: ["metrics"]
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
      - ${PWD}/../logs/app:/logs/app:ro
  
  grafana:
    image: grafana/grafana-oss:9.3.2
    container_name: tv-grafana
    env_file: [./.env]
    restart: unless-stopped
    networks: ["metrics", "backend"]
    depends_on: ["influxdb"]
    ports: ["3030:3000"]
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
