# make sure .env file exists!
version: '3.8'

networks:
  backend:
    name: "tv-backend"
    external: false
  metrics:
    name: "tv-metrics"
    external: true

services:
  app:
    container_name: teamview-app
    build: .
    command: bash -c "npx knex migrate:latest --env production; npm run start"
    networks:
      - backend
    depends_on: [db]
    ports: # HOST:INTERNAL
      - "3002:$APP_PORT"
    links: [db]
    restart: unless-stopped
    volumes:
      - ./logs/app:/app/logs

  db:
    container_name: teamview-db
    image: postgres:latest
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - backend
    ports: # HOST:INTERNAL
      - "5432:$POSTGRES_PORT"
    restart: unless-stopped
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
