# make sure .env file exists!
version: '3.8'

services:
  app:
    container_name: teamview-app
    build: .
    command: npm run start
    depends_on: [db]
    ports: # HOST:INTERNAL
      - "3002:$PORT"
    links: [db]
    restart: unless-stopped
    volumes:
      - ./logs/app:/app/logs

  db:
    container_name: teamview-db
    image: postgres:latest
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports: # HOST:INTERNAL
      - "5434:$POSTGRES_PORT"
    restart: unless-stopped
